---
title: "entropy"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{entropy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, echo=FALSE, warning=FALSE}
library(ordpatt2)
```

This function computes several types of entropy of ordinal patterns as well as the Fisher information. It combines the **HFisher**, **HRenyi**, **HShannon**, and **HTsallis** functions from the *StatOrdPattHxC* package and rewrites it using Object Oriented Programming. The examples below are taken from *StatOrdPattHxC*.


```{r, echo=TRUE, eval=TRUE}
# Time series
set.seed(1234567890, kind="Mersenne-Twister")
x <- rnorm(1000) # white noise
y <- mov.av(x, order=51) # smoothed with moving averages

# Ordinal Patterns
op.wn.4 <- OPprob2(x, emb=4)
op.ma.4 <- OPprob2(y, emb=4)

# Fisher information measures
entropy(op.wn.4, "Fisher")
entropy(op.ma.4, "Fisher")

# Renyi
entropy(op.wn.4, "Renyi")
entropy(op.ma.4, "Renyi")


# Shannon
entropy(op.wn.4, "Shannon")
entropy(op.ma.4, "Shannon")

# Tsallis
entropy(op.wn.4, "Tsallis")
entropy(op.ma.4, "Tsallis")
```
