// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// perm2
IntegerMatrix perm2(IntegerVector v);
RcppExport SEXP _ordpatt2_perm2(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(perm2(v));
    return rcpp_result_gen;
END_RCPP
}
// pi_i2_v2
int pi_i2_v2(IntegerVector pat);
RcppExport SEXP _ordpatt2_pi_i2_v2(SEXP patSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type pat(patSEXP);
    rcpp_result_gen = Rcpp::wrap(pi_i2_v2(pat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ordpatt2_perm2", (DL_FUNC) &_ordpatt2_perm2, 1},
    {"_ordpatt2_pi_i2_v2", (DL_FUNC) &_ordpatt2_pi_i2_v2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ordpatt2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
