# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

perm2 <- function(input, emb = 4L) {
    .Call('_ordpatt2_perm2', PACKAGE = 'ordpatt2', input, emb)
}

