# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

perm2 <- function(v) {
    .Call(`_ordpatt2_perm2`, v)
}

pi_i2 <- function(pat) {
    .Call(`_ordpatt2_pi_i2`, pat)
}

